[project]
name = "info-retr"
version = "0.1.0"
description = "Random indexing implementation vs vector space model"
readme = "README.md"
authors = [
    { name = "Christio02", email = "christopher.hoee@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.3",
]

[project.scripts]
info-retr = "baseline.main:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = ["baseline", "compositional_vector_model", "random_indexing"]

[tool.ty.src]
include = ["src"]
